// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrbpK_VdDkyjU17qpfUqL5TVAFQzw9IEg',
    appId: '1:62226495833:web:40cb2c9f372e964376b448',
    messagingSenderId: '62226495833',
    projectId: 'chat-ai-88c1f',
    authDomain: 'chat-ai-88c1f.firebaseapp.com',
    databaseURL: 'https://chat-ai-88c1f-default-rtdb.firebaseio.com',
    storageBucket: 'chat-ai-88c1f.appspot.com',
    measurementId: 'G-6SMLDZ1P24',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOQZ8p8fgrwxRU_ydxmG5sTQQAp3Oe06w',
    appId: '1:62226495833:android:d8f15b40b81f315b76b448',
    messagingSenderId: '62226495833',
    projectId: 'chat-ai-88c1f',
    databaseURL: 'https://chat-ai-88c1f-default-rtdb.firebaseio.com',
    storageBucket: 'chat-ai-88c1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClK3d60tU92AKDdKAxoqBBryzW6S-bR3U',
    appId: '1:62226495833:ios:67d8534ff072887376b448',
    messagingSenderId: '62226495833',
    projectId: 'chat-ai-88c1f',
    databaseURL: 'https://chat-ai-88c1f-default-rtdb.firebaseio.com',
    storageBucket: 'chat-ai-88c1f.appspot.com',
    iosClientId: '62226495833-m0juuvnh5n31putu5gtpof66380s0gjh.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatprj',
  );
}
